plugins {
    id 'groovy'
    id 'application'
}

group = 'org.uGustavoDev'
version = '1.0-SNAPSHOT'

application {
    mainClass = 'org.uGustavoDev.Main'
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.apache.groovy:groovy:5.0.8'
    testImplementation platform('org.junit:junit-bom:6.0.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

test {
    useJUnitPlatform()
}

run {
    standardInput = System.in
    jvmArgs = ["-Dfile.encoding=UTF-8"]
}