-- ===================================================
-- CANDIDATOS
-- ===================================================
INSERT INTO candidatos (id,
                        nome,
                        sobrenome,
                        data_nascimento,
                        email,
                        cpf,
                        pais,
                        estado,
                        cep,
                        descricao,
                        senha)
VALUES (1,
        'Sandubinha',
        'Oliveira',
        '1995-03-14',
        'sandubinha@email.com',
        '111.111.111-11',
        'Brasil',
        'PB',
        '58000-000',
        'Desenvolvedor em busca de novas oportunidades, com foco em backend.',
        'senha123'),
       (2,
        'Ana',
        'Ferreira',
        '1998-07-22',
        'ana.ferreira@email.com',
        '222.222.222-22',
        'Brasil',
        'PB',
        '58020-100',
        'Analista de dados apaixonada por Python e SQL.',
        'senha123'),
       (3,
        'Carlos',
        'Andrade',
        '1990-11-05',
        'carlos.andrade@email.com',
        '333.333.333-33',
        'Brasil',
        'PB',
        '58030-200',
        'Desenvolvedor backend com experiência em Java e Groovy.',
        'senha123'),
       (4,
        'Marina',
        'Costa',
        '1999-02-18',
        'marina.costa@email.com',
        '444.444.444-44',
        'Brasil',
        'PB',
        '58040-300',
        'Desenvolvedora frontend e ilustradora nas horas vagas.',
        'senha123'),
       (5,
        'Lucas',
        'Mendes',
        '1997-09-10',
        'lucas.mendes@email.com',
        '555.555.555-55',
        'Brasil',
        'PB',
        '58050-400',
        'Desenvolvedor full stack interessado em novas tecnologias e desafios.',
        'senha123');


-- ===================================================
-- EMPRESAS
-- ===================================================
INSERT INTO empresas (id,
                      nome,
                      cnpj,
                      email,
                      descricao,
                      pais,
                      cep,
                      senha)
VALUES (1,
        'Pastelsoft',
        '11.111.111/0001-11',
        'contato@pastelsoft.com.br',
        'Especializada no desenvolvimento de softwares ERP para redes de restaurantes e distribuidoras de bebida.',
        'Brasil',
        '01000-000',
        'senha123'),
       (2,
        'TechNordeste',
        '22.222.222/0001-22',
        'contato@technordeste.com.br',
        'Consultoria em dados e analytics para empresas do Nordeste.',
        'Brasil',
        '58010-000',
        'senha123'),
       (3,
        'CodeWave',
        '33.333.333/0001-33',
        'contato@codewave.com.br',
        'Empresa de tecnologia especializada no desenvolvimento de sistemas web e aplicações corporativas.',
        'Brasil',
        '58015-000',
        'senha123'),
       (4,
        'DataVision',
        '44.444.444/0001-44',
        'contato@datavision.com.br',
        'Soluções de análise de dados, inteligência artificial e automação de processos.',
        'Brasil',
        '58025-000',
        'senha123'),
       (5,
        'DevHouse',
        '55.555.555/0001-55',
        'contato@devhouse.com.br',
        'Software house focada em soluções digitais para pequenas e médias empresas.',
        'Brasil',
        '58035-000',
        'senha123');